### ISSUE TITLE
Symbol unsupported in the master password

### ISSUE THREAD

**Issue by perriea** [google-terraform-modules/terraform-google-kubernetes-engine#18]
A bug is present in Kubernetes / Provider GCP that does not allow to put symbols in the `master password`.
https://github.com/kubernetes/kubernetes/issues/65633

In my apply :
```
Error: Error applying plan:

1 error(s) occurred:

* module.gke-cluster.google_container_node_pool.new_container_cluster_node_pool: 1 error(s) occurred:

* google_container_node_pool.new_container_cluster_node_pool: Error waiting for creating GKE NodePool: All cluster resources were brought up, but the cluster API is reporting that: component "kube-apiserver" from endpoint "gke-0346b17f86677735f723-5927" is unhealthy
goroutine 151899541 [running]:
runtime/debug.Stack(0xc01048a81b, 0x3, 0x2dc1b7a)
        third_party/go/gc/src/runtime/debug/stack.go:24 +0xa7
google3/cloud/kubernetes/engine/common/errdesc.(*GKEErrorDescriptor).createErr(0x55277e0, 0xc0001aee00)
        cloud/kubernetes/engine/common/error_desc.go:199 +0x26
google3/cloud/kubernetes/engine/common/errdesc.(*GKEErrorDescriptor).WithDetail(0x55277e0, 0x312a4a0, 0xc011028200, 0xc011028200, 0x3121ac0)
        cloud/kubernetes/engine/common/error_desc.go:166 +0x40
google3/cloud/kubernetes/engine/common/healthcheck.glob..func1.1(0x0, 0xc01fefa720)
        cloud/kubernetes/engine/common/healthcheck.go:141 +0x7bb
google3/cloud/kubernetes/engine/common/call.WithTimeout(0x318d620, 0xc023a4bad0, 0x77359400, 0x8bb2c97000, 0xc0229add08,0xc023a4bad0, 0xc01fd29c00)
        cloud/kubernetes/engine/common/call.go:36 +0x153
google3/cloud/kubernetes/engine/common/healthcheck.glob..func1(0x318d620, 0xc023a4bad0, 0xc01df057a0, 0xc014e44a80, 0xc00603da00, 0x8bb2c97000, 0x0, 0x0)
        cloud/kubernetes/engine/common/healthcheck.go:137 +0x33b
google3/cloud/kubernetes/engine/server/deploy/deploy.upgradeMasterAndVerify.func3(0xc0035b9500, 0x318d560, 0xc018f17f80,0x7eff5c0509d8, 0xc00cdaa100, 0xc013756fc0, 0x0, 0xc025cbbef0, 0xc01df057a0, 0xc014e44a80, ...)
        cloud/kubernetes/engine/server/deploy/update.go:969 +0x1b3
google3/cloud/kubernetes/engine/server/deploy/deploy.upgradeMasterAndVerify(0x318d560, 0xc018f17f80, 0xc0035b9500, 0x7eff5c0509d8, 0xc00cdaa100, 0xc01df057a0, 0xc013756fc0, 0x0, 0x1, 0x0, ...)
        cloud/kubernetes/engine/server/deploy/update.go:975 +0x13f
google3/cloud/kubernetes/engine/server/deploy/deploy.(*Deployer).recreateMasterReplicas.func2(0x0, 0x0)
        cloud/kubernetes/engine/server/deploy/update.go:546 +0x23c
google3/cloud/kubernetes/engine/common/errors.CollectFns.func1(0xc00b041320, 0xc00cff2230)
        cloud/kubernetes/engine/common/errors.go:162 +0x27
created by google3/cloud/kubernetes/engine/common/errors.CollectFns
        cloud/kubernetes/engine/common/errors.go:162 +0x82
.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by NickLavrov** [comment]
In your README, you suggest using the random_string string resource. Adding this line to the options will prevent the `#` from being added:
`override_special = "'!@$%&"`
See https://www.terraform.io/docs/providers/random/r/string.html#override_special

While this doesn't fix the issue, it at least makes the suggested strategy valid.

**Comment by perriea** [comment]
Good suggestion @NickLavrov, but we do not know the extent of the bug. 
I will be more advised to change `special` value to false.

**Comment by NickLavrov** [comment]
That would work too and would be the simplest solution. To be honest it's not adding that much more randomness to include a few more types of characters. For what it's worth, I've used the `google_container_cluster` with a password with `override_special = "!@"` several times in testing, and I know passwords with those characters work.

**Comment by perriea** [comment]
Thank you for your tests and your return 👍 
I think you should share this in the Kubernetes issue.

**Comment by perriea** [comment]
The `username` and `password` have been removed for the future upgrade to GKE version 1.12.
